### ISSUE TITLE
Can't login to generate cookies

### ISSUE THREAD

**Issue by anon2478** [Witness-senpai/fakku-downloader#15]
I'm receiving this error

DevTools listening on ws://127.0.0.1:53873/devtools/browser/3429c6f3-c3c7-4a67-aa12-19e5aefae59e
Traceback (most recent call last):
  File "C:\Users\teteu\Desktop\fakku-downloader-master\fakku-downloader-master\main.py", line 140, in <module>
    main()
  File "C:\Users\teteu\Desktop\fakku-downloader-master\fakku-downloader-master\main.py", line 129, in main
    loader.init_browser(headless=False)
  File "C:\Users\teteu\Desktop\fakku-downloader-master\fakku-downloader-master\downloader.py", line 164, in init_browser
    self.__auth()
  File "C:\Users\teteu\Desktop\fakku-downloader-master\fakku-downloader-master\downloader.py", line 196, in __auth
    self.browser.find_element_by_class_name('js-submit').click()
  File "C:\Users\teteu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\teteu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\teteu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\teteu\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".js-submit"}
  (Session info: chrome=91.0.4472.106)

**Comment by armouredking** [comment]
This is caused by a change in the selector name. You can easily edit this by going to line 190 of downloader.py, and changing the line from this:
```self.browser.find_element_by_class_name('js-submit').click()```

To this:
```self.browser.find_element_by_class_name('js-submit2').click()```

**Comment by anon2478** [comment]
> This is caused by a change in the selector name. You can easily edit this by going to line 190 of downloader.py, and changing the line from this:
> `self.browser.find_element_by_class_name('js-submit').click()`
> 
> To this:
> `self.browser.find_element_by_class_name('js-submit2').click()`

Thanks, fixed the problem, but now I get this error when trying to download any manga:

"Access to XMLHttpRequest at 'https://www.fakku.net/' (redirected from 'https://books.fakku.net/hentai/somehow-im-living-with-a-bronze-high-school-elf-english/read') from origin 'https://www.fakku.net' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.", source: https://www.fakku.net/hentai/somehow-im-living-with-a-bronze-high-school-elf-english/read/page/8 (0)
[0617/154747.527:INFO:CONSOLE(2)] "Uncaught TypeError: Cannot read property 'content' of null", source: https://www.fakku.net/themes/fakku/js/reader/reader.min.js?v=2349 (2)

**Comment by anon2478** [comment]
oh it looks like I was blocked, I can't read any manga even though I connect directly to the site. Is there any way to get around this?

**Comment by armouredking** [comment]
I did not have any issues with those files, I'm guessing there is a configuration or setup difference for you. That looks similar to an error I have seen before caused by using an improper or maligned URI (ie you copy and pasted multiple links in and the actual URL is different, you can't just edit a number for example with some collections because a similarly titled series may not be spelled the same way or may have extra numbers inserted).

The aforementioned fix in downloader.py allowed me to use the downloader today (last use was in May, so the change was recent).

**Comment by anon2478** [comment]
it looks like it's a problem on my end, i'm not able to read any manga on the site in my computer or phone, maybe i got an IP block?

**Comment by armouredking** [comment]
Were you browsing Fakku while trying to download? That might trigger problems like you mentioned, I've seen that before as well. Particularly if you are browsing from different locations simultaneously (your downloader has a different IP).
