### ISSUE TITLE
 Doesn't work after logging in

### ISSUE THREAD

**Issue by Aziya66** [Witness-senpai/fakku-downloader#19]
D:\fakkudown>python main.py
Cookies file(cookies.pickle) are not detected. Please, login in next step for generate cookie for next runs.

DevTools listening on ws://127.0.0.1:9114/devtools/browser/5a1b0ca2-1cfb-444b-a694-b26aa8041e57
[13244:27320:0711/155356.280:ERROR:device_event_log_impl.cc(214)] [15:53:56.279] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Traceback (most recent call last):
  File "D:\fakkudown\main.py", line 131, in <module>
    main()
  File "D:\fakkudown\main.py", line 120, in main
    loader.init_browser(headless=False)
  File "D:\fakkudown\downloader.py", line 158, in init_browser
    self.__auth()
  File "D:\fakkudown\downloader.py", line 190, in __auth
    self.browser.find_element_by_class_name('js-submit').click()
  File "C:\Users\SSEOKK\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 564, in find_element_by_class_name
    return self.find_element(by=By.CLASS_NAME, value=name)
  File "C:\Users\SSEOKK\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\SSEOKK\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\SSEOKK\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".js-submit"}
  (Session info: chrome=91.0.4472.124)

--**_(Fakku Login)_**--

D:\fakkudown>[19972:21584:0711/155556.219:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is disabled
D:\fakkudown>
D:\fakkudown>
D:\fakkudown>

1, After logging in in step 4 of the manual, there is no response when pressing Enter.
2."Use hardware acceleration when available" is enabled in the Chrome options.
3. Even if you re-run main.py, a new chrome will pop up, and i have to log in again.

**Comment by da1geek** [comment]
Same issue here.

**Comment by Xitherun** [comment]
The element name changed again. Edit line 190 of downloader.py and change it from this:
self.browser.find_element_by_class_name('js-submit2').click()

To this:
self.browser.find_element_by_class_name('js-submit-login').click()

I just did this a few minutes ago and restarted the login process, and was able to get it working again.

**Comment by Aziya66** [comment]
Thank you. It works correctly.
