### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by RA5Dgz2L46** [Witness-senpai/fakku-downloader#2]
DevTools listening on ws://127.0.0.1:13554/devtools/browser/9765f8c4-32e3-479c-93a4-5483f227226e
invalid literal for int() with base 10: '1,269'
Downloading "black-moon-prophecy-chapter-2-english" manga.
Traceback (most recent call last):
  File "C:\Users\quawee\OneDrive\witness-senpai-fakku-downloader-master\main.py", line 77, in <module>
    main()
  File "C:\Users\quawee\OneDrive\witness-senpai-fakku-downloader-master\main.py", line 74, in main
    loader.load_all()
  File "C:\Users\quawee\OneDrive\witness-senpai-fakku-downloader-master\downloader.py", line 155, in load_all
    for page_num in tqdm(range(1, page_count + 1)):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by NyanCena** [comment]
This is a bug that I fixed in this PR: https://github.com/Witness-senpai/fakku-downloader/pull/3

Basically it's parsing out the Pages but accidentally getting the Favorites instead on Books. (This book had 1,269 favorites.)

**Comment by NyanCena** [comment]
( @RA5Dgz2L46 Not sure if the maintainer is still around, so you can clone my fork and check out the branch `improvements` until they merge in these changes 👍 )
