### ISSUE TITLE
CRL - Verification Failed

### ISSUE THREAD

**Issue by da1geek** [Witness-senpai/fakku-downloader#20]
Hello. I am unable to move past the Captcha authentication. I have verified the URLs I am trying to use are valid and have tried several different links. The only switches I use are "p" and "l" for user credentials. I complete the Captcha but it seems like the cookie(s) are not being saved as It asks to authenticate every time. Any help would be welcomed.

`C:\Users\ME\Desktop\FAKKU Downloader\fakku-downloader-master>python main.py -l myusernameishere -p mypassword
Cookies file(cookies.pickle) are not detected. Please, login in next step for generate cookie for next runs.

DevTools listening on ws://127.0.0.1:58086/devtools/browser/0e0f0ad4-f89e-42e3-a350-2fdfb74041a6
[27952:28036:0714/063155.195:ERROR:device_event_log_impl.cc(214)] [06:31:55.195] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[27952:28036:0714/063155.203:ERROR:device_event_log_impl.cc(214)] [06:31:55.203] Bluetooth: bluetooth_adapter_winrt.cc:1072 Getting Default Adapter failed.
Traceback (most recent call last):
  File "C:\Users\Jake\Desktop\FAKKU Downloader\fakku-downloader-master\main.py", line 131, in <module>
    main()
  File "C:\Users\Jake\Desktop\FAKKU Downloader\fakku-downloader-master\main.py", line 120, in main
    loader.init_browser(headless=False)
  File "C:\Users\Jake\Desktop\FAKKU Downloader\fakku-downloader-master\downloader.py", line 158, in init_browser
    self.__auth()
  File "C:\Users\Jake\Desktop\FAKKU Downloader\fakku-downloader-master\downloader.py", line 190, in __auth
    self.browser.find_element_by_class_name('js-submit2').click()
  File "C:\Users\Jake\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\Jake\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\Jake\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Jake\AppData\Roaming\Python\Python39\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=91.0.4472.124)

[27952:26504:0714/063156.844:ERROR:cast_crl.cc(384)] CRL - Verification failed.`

**Comment by Xitherun** [comment]
The element name changed again. Edit line 190 of downloader.py and change it from this:
self.browser.find_element_by_class_name('js-submit2').click()

To this:
self.browser.find_element_by_class_name('js-submit-login').click()

I just did this a few minutes ago and restarted the login process, and was able to get it working again.
