### ISSUE TITLE
Attribute error on certain galleries

### ISSUE THREAD

**Issue by ajcolon48** [Witness-senpai/fakku-downloader#23]
When I attempt to download from certain subscription based galleries I get the following error.

C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master>python main.py
Using cookies file: cookies.pickle
Traceback (most recent call last):
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\main.py", line 140, in <module>
    main()
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\main.py", line 137, in main
    loader.load_all()
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\downloader.py", line 224, in load_all
    artist = artist.string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by Xitherun** [comment]
Which gallery are you trying to download?

**Comment by ajcolon48** [comment]
There are others but right now I've been using https://www.fakku.net/hentai/eros-in-wonderland-chapter-3-english as a test.

**Comment by ajcolon48** [comment]
Did a fresh install.  Works now.  There must have been a change in the code.
