### ISSUE TITLE
started getting errors in the middle of download

### ISSUE THREAD

**Issue by madmanmaxmoan** [Witness-senpai/fakku-downloader#30]
> DevTools listening on ws://127.0.0.1:50461/devtools/browser/a1fc2340-888b-4d31-81da-8abff59d0b66
Traceback (most recent call last):
  File "C:\Users\Jason\Desktop\fucker\main.py", line 142, in <module>
    main()
  File "C:\Users\Jason\Desktop\fucker\main.py", line 133, in main
    loader.init_browser(headless=True)
  File "C:\Users\Jason\Desktop\fucker\downloader.py", line 163, in init_browser
    self.__set_cookies()
  File "C:\Users\Jason\Desktop\fucker\downloader.py", line 169, in __set_cookies
    cookies = pickle.load(f)
EOFError: Ran out of input

**Comment by Witness-senpai** [comment]
Just try delete the old .pickle file and the script will create a new correct .pickle during the new run.
