### ISSUE TITLE
Error using a fresh install

### ISSUE THREAD

**Issue by ajcolon48** [Witness-senpai/fakku-downloader#31]
C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master>python main.py
Using cookies file: cookies.pickle

DevTools listening on ws://127.0.0.1:62633/devtools/browser/0362f116-5f1f-4fb2-bb76-34f084c04419
<class 'str'>
Traceback (most recent call last):
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\main.py", line 142, in <module>
    main()
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\main.py", line 138, in main
    loader.load_all()
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\downloader.py", line 221, in load_all
    page_count = self.__get_page_count(self.browser.page_source)
  File "C:\Users\Owner\OneDrive\Desktop\fakku-downloader-master\downloader.py", line 306, in __get_page_count
    return int(pages_info[0])
ValueError: invalid literal for int() with base 10: 'eRomantic'

**Comment by Benjki** [comment]
What did you try to download? A book or a collection? If it is a 1 page book, check the other post. I've modified it to accept 1 page book else link it. If it is a collection, download them as books instead. I'm not the original author and I don't want to start fixing everything in this horrible code base.

**Comment by ajcolon48** [comment]
Update fixed issue
