### ISSUE TITLE
Error while attempting to download

### ISSUE THREAD

**Issue by Ramrod-RMC** [Witness-senpai/fakku-downloader#33]
I am using the latest build. I was downloading successfully earlier, then I had an error with one manga. After closing the command prompt and launching the script again, I get the following error message

G:\Program Files (x86)\Fakku Downloader>python main.py
Using cookies file: cookies.pickle

DevTools listening on ws://127.0.0.1:52748/devtools/browser/27c763ee-900c-451f-9a36-e4e9921fcfb8
<class 'str'>
Traceback (most recent call last):
File "G:\Program Files (x86)\Fakku Downloader\main.py", line 142, in <module>
main()
File "G:\Program Files (x86)\Fakku Downloader\main.py", line 138, in main
loader.load_all()
File "G:\Program Files (x86)\Fakku Downloader\downloader.py", line 221, in load_all
page_count = self.__get_page_count(self.browser.page_source)
File "G:\Program Files (x86)\Fakku Downloader\downloader.py", line 306, in __get_page_count
return int(pages_info[0])
ValueError: invalid literal for int() with base 10: 'No'

**Comment by Ramrod-RMC** [comment]
Nevermind, one day later and the issue appears resolved.

**Comment by Ramrod-RMC** [comment]
Error appeared to have disappeared, but after downloading one manga normally, the issue has returned
