### ISSUE TITLE
Same problem as Issue #2

### ISSUE THREAD

**Issue by Havoc587** [Witness-senpai/fakku-downloader#9]
Hi, I'm getting this but unlike issue #2, downloading "black-moon-prophecy-chapter-2-english" works fine but this doesn't.

DevTools listening on ws://127.0.0.1:3804/devtools/browser/22e2d491-2afb-4412-82bb-0403890a1948

Downloading "chika-chans-funtime-english" manga.
Traceback (most recent call last):
  File "C:\Users\Havoc\Desktop\fakku-downloader-master\main.py", line 131, in <module>
    main()
  File "C:\Users\Havoc\Desktop\fakku-downloader-master\main.py", line 128, in main
    loader.load_all()
  File "C:\Users\Havoc\Desktop\fakku-downloader-master\downloader.py", line 222, in load_all
    for page_num in tqdm(range(1, page_count + 1)):
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by Witness-senpai** [comment]
Please tell me which full URL do you use? How do you run the script? What options are used?

**Comment by Havoc587** [comment]
https://www.fakku.net/hentai/chika-chans-funtime-english

I just typed in "python main.py", without any of the option commands, into the cmd. From what I can tell, only a select few links gave this error.

**Comment by Witness-senpai** [comment]
Following this link in the browser, I received an error: “There was a problem. Content does not exist.". Could the url be the problem?

**Comment by Havoc587** [comment]
You probably need to log in to see it.

**Comment by Havoc587** [comment]
Strange, I made a new fakku account and that link doesn't work anymore. Once I switched back to my main account, it works perfectly fine. The script might be fine, seems like fakku is limiting access to certain doujins.

**Comment by armouredking** [comment]
This is reproducable - it is caused by Fakku releasing books. The books seem to screw up the counting method. Make sure you point your url at the non-book version to perform the download.

Steps to reproduce:

1. Find a book that includes a story that was previously released
2. Try to use the link to the "book" copy vice the "standalone" copy
3. Receive this error.
